# Build e preparação para Railway
name: 🚂 Railway Ready

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: ☕ Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: 🧪 Executar testes
      run: mvn test

    - name: 🔨 Build da aplicação
      run: mvn clean package -DskipTests

    - name: ✅ Verificar build
      run: |
        echo "✅ Build concluído com sucesso!"
        echo "📦 JAR criado: $(ls target/*.jar)"
        echo "🚂 Pronto para deploy no Railway!"
        echo ""
        echo "🔗 Para fazer deploy:"
        echo "1. Acesse: https://railway.app"
        echo "2. New Project → Deploy from GitHub repo"
        echo "3. Selecione este repositório"
        echo "4. Aguarde o deploy automático"
